# Generated by Django 5.1.6 on 2025-02-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('IN', 'INDIAN'), ('CH', 'CHINESE'), ('IT', 'ITALIAN'), ('MX', 'MEXICAN'), ('FF', 'FAST FOOD'), ('OT', 'OTHER')], default='OT', max_length=2),
        ),
    ]
